# Generated by Django 2.2.6 on 2019-12-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191218_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rel_url',
            field=models.CharField(default='cv', max_length=10, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
